### ISSUE TITLE
Flying takes damage and kills the player.

### ISSUE THREAD

**Issue by excaliburkim** [EricLangezaal/PetDragon#10] opened 2023-04-10 08:24 UTC
We are having so much fun playing with this plug-in. Thanks for developing it.
Set the dragon's [speed-multiplier] setting to 3.
Moving up and down while flying takes damage and kills the player.
could you please solve this problem?

**Comment by EricLangezaal** [comment] 2023-04-11 08:45
Glad to hear you like my plugin! Yes that is definitely unfortunate. To help me resolve this, could you answer a couple of  questions for me?
1. Just to be sure, this happens for the player which is riding the dragon right? Because it is intentional that dragons can harm external players, but they should indeed not harm their own owner.
2. Does this happen only at dragon speed multipliers of 3 and above, or can you also reproduce it at slower dragon speeds?
3. What is the death message/reason you get (in chat or on the death screen) when a player dies because of the dragon flying?

**Comment by excaliburkim** [comment] 2023-04-12 01:28
It's not easy to change the settings because the server is currently running.
We were flying and suddenly died with the message "hit the ground too hard".

**Comment by excaliburkim** [comment] 2023-04-12 01:28
> Glad to hear you like my plugin! Yes that is definitely unfortunate. To help me resolve this, could you answer a couple of questions for me?
> 
> 1. Just to be sure, this happens for the player which is riding the dragon right? Because it is intentional that dragons can harm external players, but they should indeed not harm their own owner.
> 2. Does this happen only at dragon speed multipliers of 3 and above, or can you also reproduce it at slower dragon speeds?
> 3. What is the death message/reason you get (in chat or on the death screen) when a player dies because of the dragon flying?

It's not easy to change the settings because the server is currently running.
We were flying and suddenly died with the message "hit the ground too hard".

**Comment by EricLangezaal** [comment] 2023-04-12 08:43
You don't need to restart the server to change such settings, simply run `/dragon reload`. 
Thank you for confirming the death message. Just to confirm, this happened when you were the only passenger of a dragon?

**Comment by excaliburkim** [comment] 2023-05-03 17:47
The same appears when it is 1.0.
See the video link.

[http://a-r-c.kr/mc/4/2023_05_04_02_32_41_374.mp4](http://a-r-c.kr/mc/4/2023_05_04_02_32_41_374.mp4)

**Comment by EricLangezaal** [comment] 2023-05-05 12:28
I cannot read the death message since it is not in English, so the video unfortunately doesn't help me much. Is it always "... hit the ground too hard"?

 I double checked it, but this damage should definitely be [prevented](https://github.com/EricLangezaal/PetDragon/blob/master/core/src/main/java/com/ericdebouwer/petdragon/listeners/DragonListener.java#L82-L87) if you are riding a dragon and just have my plugin influencing damage. This might be caused by a conflicting plugin which is changing the damage after my plugin does that, which other plugins do you have?

**Comment by excaliburkim** [comment] 2023-05-05 17:24
Sorry. I had to translate it and send it, but I forgot.
"hit the ground too hard" is correct.
With 130 plugins, it seems hard to find :(
Thanks for your help.

**Comment by EricLangezaal** [comment] 2023-05-05 17:27
Okay I will have a look if I can reproduce it when I update this plugin next (no idea when I will have time for that tbh). If I can't reproduce it, there's unfortunately little I can do.

**Comment by EricLangezaal** [comment] 2023-05-28 13:20
This should be fixed in the latest update, please have a look! I found out that suffocation damage wasn't properly blocked. When I added that to the blocked list, I could no longer damage the player while flying. If it works for you, don't forget to leave a review:) If not, please re-open this issue/another issue.

**Closed as completed by EricLangezaal** 2023-05-28 13:20 UTC
