### ISSUE TITLE
Dragons lose their name on ChunkLoad

### ISSUE THREAD

**Issue by JoelGodOfwar** [EricLangezaal/PetDragon#1] opened 2020-10-24 21:39 UTC
@EricLangezaal 
Please add a Persistent Data Container for the isSilent boolean, and then set setSilent(boolean) for the dragon, so that PetDragon will work with my Silence Mobs plugin. Or keep the custom name of the dragon on chunkloadevent.

Translated to Nederlands by google:
Voeg een permanente gegevenscontainer toe voor de isSilent boolean, en stel vervolgens setSilent (boolean) in voor de draak, zodat PetDragon zal werken met mijn Silence Mobs-plug-in. Of bewaar de aangepaste naam van de draak op chunkloadevent.

**Comment by EricLangezaal** [comment] 2020-10-24 21:57
This is not a bug in my plugin, but instead has to do with functionality you want to add onto it. I will therefore not edit my plugin to accommodate something highly specific required by you only (nor do I have the time to do so).
More importantly you are asking me to change something even though you could completely do this from your plugin (and as this is something that only matters for your plugin you should). Example: You can fix this yourself by listening to ChunkLoadEvent and EntitySpawnEvent. Whenever a chunk loads with enderdragons in them, save your custom data for each dragon to some sort of map based on their location. Now whenever a enderdragon spawns in EntitySpawnEvent and its coordinates match, you know to put your data back. Sure this is a little more work, however it is your plugin after all :).

**Comment by EricLangezaal** [comment] 2020-11-07 12:19
I managed to properly fix this issue in the new update! When respawning the dragon, my plugin now copies all of its NBT tags, which means it should also save the isSilent boolean and **any** persistentDataContainer stuff you put on it. In case you are interested how it works, check out the `copyFrom(EnderDragon dragon)` method in [this class](https://github.com/EricLangezaal/PetDragon/blob/master/src/main/java/com/ericdebouwer/enderdragonNMS/PetEnderDragon_v1_16_R3.java). this means that from your plugin, you can just treat the PetDragons like any normal Entity and my plugin will make sure it copies over all data. 

Let me know what you think of this! I will probably close this issue soon, but don't know if that still allows you to respond so will wait a little.

**Comment by JoelGodOfwar** [comment] 2020-11-07 21:55
The only part I'm curious about is "this.load(nbt);", I don't see a load function in the class, so does EntityEnderDragon have a load function for nbt data? Thank you for the extra time to ask about this, before you close it.

**Comment by EricLangezaal** [comment] 2020-11-08 11:37
Well you are correct that my PetEnderDragon classes inherit the method. But the inherency chain is a little more complex. My class inherits from EntityEnderDragon, which is a subclass of EntityInsentient, a subclass of EntityLiving, which in term inherits from Entity. This base class it the core of every entity in Minecraft and contains a couple of base methods/functionality, like storing and loading entities to NBT. These methods are normally used by Minecraft internally, but I figured out you can use them to clone data from one entity to another too.

**Closed as completed** 2020-11-13 21:14 UTC
